name: "Oscar CI (package tests)"

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: oscar-system/oscar-ci-action/configure@master
      with:
        julia: "1.5.3"
        package: GAP
        ref: ${{ github.sha }}
        repository: ${{ github.repository }}
        buildtype: master
        test: packages
    - uses: oscar-system/oscar-ci-action/install@master
    - uses: oscar-system/oscar-ci-action/test@master
    - uses: actions/upload-artifact@v2
      with:
        name: logs
        path: workspace/logs/
